export const DEMO_PERSONAS = [
  {
    id: 'p_01',
    role: 'patient',
    username: 'patient_priya',
    name: 'Priya Sharma',
    subtext: 'Hindi / English • Post-Op Appendectomy (Day 6)',
    patientId: 'p_01',
    lang: 'hi',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80'
  },
  {
    id: 'p_02',
    role: 'patient',
    username: 'patient_ramesh',
    name: 'Ramesh Kumar',
    subtext: 'Kannada • Congestive Heart Failure (High Risk)',
    patientId: 'p_02',
    lang: 'kn',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80'
  },
  {
    id: 'doc_01',
    role: 'doctor',
    username: 'doc_ching',
    name: 'Dr. Ching Ming Yang',
    specialization: 'Cardiologist',
    experience_years: 14,
    rating: 5.0,
    session_fee: 92,
    clinic_address: '300 Pasteur DR, Apollo Metro Hub',
    subtext: 'Cardiologist • 14+ yrs exp • $92/session',
    badgeText: 'Speaks HI',
    doctorId: 'doc_01',
    lang: 'en',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'doc_05',
    role: 'doctor',
    username: 'doc_rajesh',
    name: 'Dr. Rajesh Rao',
    specialization: 'General Physician',
    experience_years: 16,
    rating: 5.0,
    session_fee: 60,
    clinic_address: 'OPD Block 1, Central Medical',
    subtext: 'General Physician • 16+ yrs exp • $60/session',
    badgeText: 'Speaks HI',
    doctorId: 'doc_05',
    lang: 'kn',
    avatar: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'doc_02',
    role: 'doctor',
    username: 'doc_marc',
    name: 'Dr. Marc Lee',
    specialization: 'Cardiologist',
    experience_years: 10,
    rating: 4.6,
    session_fee: 85,
    clinic_address: 'Cardio Wing B, Sehat Hospital',
    subtext: 'Cardiologist • 10+ yrs exp • $85/session',
    badgeText: 'Translates via Sarvam AI',
    doctorId: 'doc_02',
    lang: 'en',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'doc_03',
    role: 'doctor',
    username: 'doc_olivia',
    name: 'Dr. Olivia Bennett',
    specialization: 'Therapist & Clinical Psychologist',
    experience_years: 8,
    rating: 4.3,
    session_fee: 75,
    clinic_address: 'Mind Care Center, Sector 4',
    subtext: 'Therapist & Clinical Psychologist • 8+ yrs exp • $75/session',
    badgeText: 'Translates via Sarvam AI',
    doctorId: 'doc_03',
    lang: 'en',
    avatar: 'https://images.unsplash.com/photo-1594824813586-77823f66c9bb?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'doc_04',
    role: 'doctor',
    username: 'doc_ethan',
    name: 'Dr. Ethan Roberts',
    specialization: 'Pediatrician',
    experience_years: 12,
    rating: 4.5,
    session_fee: 80,
    clinic_address: "Children's Health Pavilion",
    subtext: 'Pediatrician • 12+ yrs exp • $80/session',
    badgeText: 'Translates via Sarvam AI',
    doctorId: 'doc_04',
    lang: 'en',
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'adm_01',
    role: 'admin',
    username: 'admin_vikram',
    name: 'Admin Vikram Malhotra',
    subtext: 'Hospital Fleet & Resource Command Center',
    adminId: 'adm_01',
    lang: 'en',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80'
  }
];
